default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2

development:
  <<: *default
  database: atemporal_development

test:
  <<: *default
  database: atemporal_test

production:
  <<: *default
  template: template0
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
