#cloud-config

write_files:
  - path: /etc/atemporal-worker
    encoding: base64
    content: |
      <%= payload %>

coreos:
  units:
    - name: atemporal-worker.service
      command: start
      content: |
        [Unit]
        Description=Atemporal Worker
        After=docker.service
        Requires=docker.service
        
        [Service]
        TimeoutStartSec=10m
        ExecStartPre=-/usr/bin/docker kill atemporal-worker
        ExecStartPre=-/usr/bin/docker rm atemporal-worker
        ExecStartPre=/usr/bin/docker pull <%= image %>
        ExecStartPre=/usr/bin/curl -X PATCH <%= formatted_callback_server %>
        ExecStart=/usr/bin/docker run -P --env-file=/etc/atemporal-worker --name atemporal-worker <%= image %>
        ExecStop=/usr/bin/docker stop atemporal-worker
        ExecStopPost=/usr/bin/curl -X DELETE <%= formatted_callback_server %>
