#!/bin/bash -e

APP_NAME="atemporal"
APP_PATH="/var/www/$APP_NAME"

case "$1" in
  configure)
    chown -R www-data. /var/www/$APP_NAME
    test -f /etc/nginx/sites-enabled/default && rm /etc/nginx/sites-enabled/default
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
