#cloud-config

coreos:
  etcd:
    discovery: DISCOVERY
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: httpsrv.service
      command: start
      content: |
        [Unit]
        Description=Atemporal http
        After=docker.service
        Requires=docker.service
        
        [Service]
        TimeoutStartSec=10m
        ExecStartPre=-/usr/bin/docker kill atemporal
        ExecStartPre=-/usr/bin/docker rm atemporal
        ExecStartPre=/usr/bin/docker pull DOCKER_USERNAME/atemporal
        ExecStart=/usr/bin/docker run --name httpsrv -p 80:80 DOCKER_USERNAME/atemporal
        ExecStop=/usr/bin/docker stop atemporal
