#!/bin/bash

image="nginx:1.9"
time="2015-04-25T05:27:27.069Z"
server="http://localhost:3000/jobs.json"
payload=$(echo 'NAME="bond, james bond"' | base64)

curl -vvv  -X POST -d "image=$image&time=$time&payload=$payload" $server
