runtime:
  image: atemporal/runtime
  command: /scripts/runtime 
  ports:
    - 8080:80
  links:
    - postgresql
  volumes:
    - containers/scripts:/scripts
    - containers/tmp/build:/build
  environment:
    - RAILS_ENV=production
    - DATABASE_URL=postgres://locaweb:locaweb@postgresql/atemporal_production
    - SECRET_KEY_BASE=c39362cda691f8394182f72c0c5b02bb6da54a9be6e374e948a7672db636de4e284a2e0f6dbe16b92f885d95e8075b2cfbcadc31dd2b4dd3e94eaac8711e1b3e

postgresql:
  image: locaweb/postgresql
