builder:
  image: atemporal/builder
  command: /scripts/builder
  volumes:
    - ../../webapp:/source
    - containers/scripts:/scripts
    - containers/images/runtime/package:/build
    - containers/tmp/cache:/opt/atemporal/vendor/bundle
