#!/bin/bash -le

echo "-----------------------------------------------------------------------"
ip addr show eth0 | grep "inet "
echo "-----------------------------------------------------------------------"

pushd /var/www/atemporal
  bundle exec rake db:setup
popd

/start
