#!/bin/bash -le

rsync -a \
  --exclude 'log' \
  --exclude 'bricky' \
  --exclude 'terraform' \
  --stats /source/* /opt/atemporal

pushd /opt/atemporal
  bundle install --deployment --without=development:test
popd

pushd /opt
  tar czf /build/application.tar atemporal
popd
