source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'aasm'
gem 'puma'
gem 'daemons'
gem 'foreman'
gem 'aws-sdk'
gem 'roar-rails'
gem 'delayed_job_active_record'

group :development, :test do
  gem 'pry'
  gem 'spring'
  gem 'dotenv-rails'
  gem 'better_errors'
end

group :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end
